@extends('layouts.app')

@section('title', 'Quote Request — ' . ($itinerary->tour_name ?? 'Your Custom Tour'))

@push('styles')
<link rel="stylesheet" href="{{ global_asset('css/diy.css') }}">
@endpush

@section('content')
<div class="container diy-quote-container">

    {{-- Header --}}
    <div class="quote-header">
        <div class="quote-status-badge {{ $session->status }}">
            {{ ucfirst($session->status) }}
        </div>
        <h1>{{ $itinerary->tour_name ?? 'Your Custom Tour' }}</h1>
        <p class="quote-subtitle">
            @if($session->status === 'pending_review')
                Your quote request is under review. Our team will reply within 24 hours.
            @elseif($session->status === 'quoted')
                Your quote is ready! Review the details below.
            @else
                Review your itinerary and pricing below.
            @endif
        </p>
    </div>

    <div class="quote-grid">

        {{-- LEFT COLUMN: Itinerary summary --}}
        <div class="quote-left">

            {{-- Official quote box (if generated by admin) --}}
            @if($latestQuote = $itinerary?->latestQuote)
            <div class="official-quote-box">
                <div class="quote-box-header">
                    <i class="fas fa-file-invoice"></i> Official Quote
                </div>
                <div class="quote-amount">
                    ₱{{ number_format($latestQuote->quoted_price_php) }}
                    <small>per person</small>
                </div>
                <div class="quote-validity">
                    Valid until: {{ $latestQuote->valid_until?->format('F j, Y') ?? 'Until further notice' }}
                </div>
                @if($latestQuote->terms_conditions)
                <div class="quote-terms">
                    <strong>Terms &amp; Conditions:</strong>
                    <p>{{ $latestQuote->terms_conditions }}</p>
                </div>
                @endif
                @if($latestQuote->status === 'pending' && auth()->check() && !$latestQuote->isExpired())
                <div class="quote-actions mt-3">
                    <a href="{{ route('diy.checkout.show', $session->session_token) }}" class="btn btn-primary btn-lg" style="width:100%">
                        <i class="fas fa-credit-card"></i> Proceed to Payment
                    </a>
                    <p class="text-muted mt-2" style="font-size:.8rem;text-align:center">
                        Or contact us at <a href="mailto:bookings@discovergroup.com">bookings@discovergroup.com</a>
                    </p>
                </div>
                @elseif($latestQuote->status === 'accepted')
                <div class="quote-actions mt-3">
                    <div style="background:#dcfce7;border:1px solid #86efac;border-radius:.5rem;padding:1rem;text-align:center;color:#166534;font-weight:600">
                        <i class="fas fa-check-circle"></i> This quote has been paid
                    </div>
                    <a href="{{ route('diy.checkout.confirmation', $session->session_token) }}" class="btn btn-outline btn-full mt-2">
                        <i class="fas fa-receipt"></i> View Confirmation
                    </a>
                </div>
                @endif
            </div>
            @endif

            {{-- Pricing breakdown --}}
            @php $pricing = $itinerary?->pricing_data ?? []; @endphp
            @if(!empty($pricing))
            <div class="pricing-card">
                <h3>💰 Cost Breakdown <small>(per person)</small></h3>
                @foreach([
                    ['accommodation',  'Accommodation',       'fa-bed'],
                    ['transportation', 'Transportation',      'fa-train'],
                    ['activities',     'Activities & Entries','fa-ticket-alt'],
                    ['meals',          'Meals',               'fa-utensils'],
                    ['guide_services', 'Tour Guide Services', 'fa-user-tie'],
                    ['visa_insurance', 'Visa & Insurance',    'fa-shield-alt'],
                ] as [$key, $label, $icon])
                @if(isset($pricing[$key]))
                <div class="pricing-line">
                    <span><i class="fas {{ $icon }}"></i> {{ $label }}</span>
                    <span>₱{{ number_format($pricing[$key] / max(1, $pricing['group_size'] ?? 1)) }}</span>
                </div>
                @endif
                @endforeach
                <div class="pricing-divider"></div>
                <div class="pricing-line">
                    <span>Subtotal</span>
                    <span>₱{{ number_format(($pricing['subtotal'] ?? 0) / max(1, $pricing['group_size'] ?? 1)) }}</span>
                </div>
                <div class="pricing-line">
                    <span>Service Fee ({{ $pricing['markup_percent'] ?? 15 }}%)</span>
                    <span>₱{{ number_format(($pricing['markup'] ?? 0) / max(1, $pricing['group_size'] ?? 1)) }}</span>
                </div>
                <div class="pricing-divider"></div>
                <div class="pricing-line pricing-total">
                    <span>TOTAL PER PERSON</span>
                    <span>₱{{ number_format($pricing['total_per_person'] ?? 0) }}</span>
                </div>
                @if(($pricing['group_size'] ?? 1) > 1)
                <div class="pricing-line pricing-group-total">
                    <span>For {{ $pricing['group_size'] }} people</span>
                    <span>₱{{ number_format($pricing['total_group'] ?? 0) }}</span>
                </div>
                @endif
            </div>
            @endif

            {{-- Validation results --}}
            @php $validation = $itinerary?->validation_results ?? []; @endphp
            @if(!empty($validation))
            <div class="validation-card">
                <h3>🔍 Plan Quality Check</h3>
                <div class="score-row">
                    <div class="score-circle {{ ($validation['overall_score'] ?? 0) >= 80 ? 'score-good' : (($validation['overall_score'] ?? 0) >= 60 ? 'score-warn' : 'score-bad') }}">
                        {{ $validation['overall_score'] ?? '--' }}<small>/100</small>
                    </div>
                    <div class="score-stars">
                        @for($i = 1; $i <= 5; $i++)
                            <i class="fas fa-star {{ $i <= round(($validation['overall_score'] ?? 0) / 20) ? 'text-warning' : 'text-muted' }}"></i>
                        @endfor
                        <p class="mt-1 text-muted small">{{ $validation['recommendation'] ?? '' }}</p>
                    </div>
                </div>

                @if(!empty($validation['issues']))
                <div class="validation-group issues">
                    <strong>❌ Must Fix Before Subscribing:</strong>
                    @foreach($validation['issues'] as $issue)
                    <div class="validation-item">
                        <span>{{ $issue['message'] }}</span>
                        <small>{{ $issue['suggestion'] ?? '' }}</small>
                    </div>
                    @endforeach
                </div>
                @endif

                @if(!empty($validation['warnings']))
                <div class="validation-group warnings">
                    <strong>⚠️ Warnings:</strong>
                    @foreach($validation['warnings'] as $warn)
                    <div class="validation-item warn">
                        <span>{{ $warn['message'] }}</span>
                        <small>{{ $warn['suggestion'] ?? '' }}</small>
                    </div>
                    @endforeach
                </div>
                @endif

                @if(!empty($validation['good_points']))
                <div class="validation-group good">
                    <strong>✅ Good Points:</strong>
                    @foreach($validation['good_points'] as $gp)
                    <div class="validation-item good">{{ $gp }}</div>
                    @endforeach
                </div>
                @endif
            </div>
            @endif

        </div>{{-- .quote-left --}}

        {{-- RIGHT COLUMN: Share, book actions --}}
        <div class="quote-right">

            {{-- Action panel --}}
            <div class="action-panel">
                <a href="{{ route('diy.builder', $session->session_token) }}" class="btn btn-outline btn-full">
                    <i class="fas fa-edit"></i> Back to Editor
                </a>

                @if($session->status === 'draft')
                <form action="{{ route('diy.request-quote', $session->session_token) }}" method="POST">
                    @csrf
                    <button type="submit" class="btn btn-primary btn-full mt-2">
                        <i class="fas fa-paper-plane"></i> Submit for Quote
                    </button>
                </form>
                @endif

                <button class="btn btn-outline btn-full mt-2" onclick="shareTour()">
                    <i class="fas fa-share-alt"></i> Share This Plan
                </button>

                <button class="btn btn-outline btn-full mt-2" onclick="copyShareLink()">
                    <i class="fas fa-link"></i> Copy Share Link
                </button>
            </div>

            {{-- Itinerary days summary --}}
            @php $dayByDay = $itinerary?->itinerary_data['day_by_day'] ?? []; @endphp
            @if(!empty($dayByDay))
            <div class="day-summary-card">
                <h3>📅 Day-by-Day Summary</h3>
                @php $lastCity = ''; @endphp
                @foreach($dayByDay as $day)
                @if($day['city'] !== $lastCity)
                    @php $lastCity = $day['city']; @endphp
                    <div class="day-city-header">
                        <span class="city-dot"></span>
                        <strong>{{ $day['city'] }}, {{ $day['country'] }}</strong>
                    </div>
                @endif
                <div class="day-row">
                    <span class="day-num">Day {{ $day['day'] }}</span>
                    <div class="day-activities">
                        @foreach($day['activities'] ?? [] as $act)
                        <span class="activity-tag {{ $act['included'] ? 'included' : 'optional' }}">
                            {{ $act['name'] }}
                            @if(!$act['included']) <em>(+₱{{ number_format($act['cost_if_optional'] ?? 0) }})</em> @endif
                        </span>
                        @endforeach
                    </div>
                </div>
                @endforeach
            </div>
            @endif

            {{-- Transportation summary --}}
            @php $transfers = $itinerary?->itinerary_data['transportation'] ?? []; @endphp
            @if(!empty($transfers))
            <div class="transport-card">
                <h3>🚆 Transfers</h3>
                @foreach($transfers as $t)
                <div class="transfer-row">
                    <span>Day {{ $t['day'] ?? '?' }}</span>
                    <span>{{ $t['from'] ?? '' }} → {{ $t['to'] ?? '' }}</span>
                    <span>{{ $t['method'] ?? '' }} ({{ $t['duration_hours'] ?? '' }}h)</span>
                </div>
                @endforeach
            </div>
            @endif

            {{-- Invite collaborators --}}
            @auth
            <div class="invite-card" id="invitePanel">
                <h3>👥 Invite Collaborators</h3>
                <div class="form-group">
                    <input type="email" id="inviteEmail" class="form-control form-control-sm" placeholder="friend@example.com">
                </div>
                <div class="form-group">
                    <select id="invitePermission" class="form-control form-control-sm">
                        <option value="view">Can view only</option>
                        <option value="suggest">Can suggest changes</option>
                        <option value="edit">Can edit freely</option>
                    </select>
                </div>
                <button class="btn btn-outline btn-sm btn-full" onclick="sendInvite()">
                    <i class="fas fa-user-plus"></i> Send Invitation
                </button>
            </div>
            @endauth

        </div>{{-- .quote-right --}}

    </div>{{-- .quote-grid --}}

</div>{{-- .diy-quote-container --}}
@endsection

@push('scripts')
<script>
const SESSION_TOKEN = '{{ $session->session_token }}';
const INVITE_URL = '{{ route("diy.invite", $session->session_token) }}';

function copyShareLink() {
    const url = window.location.href;
    navigator.clipboard.writeText(url).then(() => {
        alert('Link copied to clipboard!');
    });
}

function shareTour() {
    if (navigator.share) {
        navigator.share({
            title: '{{ addslashes($itinerary->tour_name ?? "My Custom Tour") }}',
            text: 'Check out my custom plan!',
            url: window.location.href
        });
    } else {
        copyShareLink();
    }
}

function sendInvite() {
    const email = document.getElementById('inviteEmail').value.trim();
    const perm  = document.getElementById('invitePermission').value;
    if (!email || !email.includes('@')) { alert('Please enter a valid email address.'); return; }

    fetch(INVITE_URL, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content,
        },
        body: JSON.stringify({ email, permission_level: perm }),
    })
    .then(r => r.json())
    .then(d => {
        alert(d.message || d.success ? 'Invitation sent!' : 'Failed to send invite.');
        if (d.success) document.getElementById('inviteEmail').value = '';
    })
    .catch(() => alert('Failed to send invitation. Please try again.'));
}
</script>
@endpush
